import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-900 text-gray-400 mt-8">
      <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div className="xl:grid xl:grid-cols-3 xl:gap-8">
          <div className="space-y-8 xl:col-span-1">
            <div className="text-white text-2xl font-bold">Mahama News TV</div>
            <p className="text-gray-400 text-base">All content is dynamically generated by Google's Gemini API for demonstration purposes.</p>
          </div>
          <div className="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
            <div className="md:grid md:grid-cols-2 md:gap-8">
              <div>
                <h3 className="text-sm font-semibold text-gray-200 tracking-wider uppercase">News</h3>
                <ul className="mt-4 space-y-4">
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Home</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">World</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Politics</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Business</a></li>
                </ul>
              </div>
              <div className="mt-12 md:mt-0">
                <h3 className="text-sm font-semibold text-gray-200 tracking-wider uppercase">Categories</h3>
                <ul className="mt-4 space-y-4">
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Sport</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Technology</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">History</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Economy</a></li>
                </ul>
              </div>
            </div>
            <div className="md:grid md:grid-cols-2 md:gap-8">
              <div>
                <h3 className="text-sm font-semibold text-gray-200 tracking-wider uppercase">More</h3>
                <ul className="mt-4 space-y-4">
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Science</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Health</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Culture</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Entertainment</a></li>
                </ul>
              </div>
              <div className="mt-12 md:mt-0">
                <h3 className="text-sm font-semibold text-gray-200 tracking-wider uppercase">Legal</h3>
                <ul className="mt-4 space-y-4">
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Terms of Use</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Privacy Policy</a></li>
                  <li><a href="#" className="text-base text-gray-400 hover:text-white">Cookies</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-12 border-t border-gray-700 pt-8">
          <p className="text-base text-gray-400 xl:text-center">&copy; 2024 Mahama News TV. Content is AI-generated and for demonstration purposes only.</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;